langauge: node_js
node_js: "10"

jobs:
  include:
    - language: node_js
      node_js: "10"
      before_install: "cd packages/example"
      install: "npm install"

      script: "npm test" # 默认执行的脚本
      after_success: "npm run build"
      name: "build-1"

notifications:
  email:
    recipients:
      - xjiaxiang_86@163.com
    on_success: always # default: change
    on_failure: always # default: always
