language: node_js
node_js: '10'

#stages:
#  - stage-2
#  - name: build
#    if: branch = feature/example

cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: build
      language: node_js
      node_js: '10'
      name: build-1
      deploy:
        provider: npm
        email: xjiaxiang86@gmail.com
        api_key:
          secure: v62JWuoItVwItO1yZ4gH5gWNe/KoDE6UuAqrMpKFRYj/gggB2oJIk3r/+eqEwZ/BMdh+g4ktoDAjglxKnYZJhEOD02+kecpJs6x9wqVTxS+iD3Jh14X+2uhzedhNNa4T0nEePT7zDuGzfKaKaMsciGLTwPnLlYpHlWpEt8x+JeJJHSYj6/0G/jQ6gAXxuPsbuqa1jJNS+VBASdruSL/cCUBW2S30SLc6EIzhJcC3b7//cGrHjzCPU8fTer3Vkkpo62+eW0ka+A2Wcbikp/3Ml8fo4s2974oonFPHALMV4dRgM1AVu959I/jv61VEG9W+kV/+YaULExwf1exvKC18jQGlvqIhKA8Tvar76cS0DWlsZGIfJw/u/3t61tN8BLOL8N00zDhd8EgwSiAxUugrLrJ5lbV1ugqCTq0pBeo+k7wS+T6hcyCOQJqrwSiHY3E2AiFf0Ql+V4LzFs6+FszRZYs7skmq799xXTWvR4z/yfxCpoq25VrxT6Ajc4ASqwTZzXfNRIAigQJYc1fvdrfGJLhqUrBmsvMJCm+nREECRRsSuHbSQ6Agq8xqmDaMrDoug2FgmnC6m0AjB+QtS/DEqMYE7Alo3uc5eFeXFA4kYy6vO4w4HYCnpblfaTgSELjTDj4UgTOKDFzjbLQLTBeOL06ujrMshWr1bhE1kdm+a7Q=
        on:
          repo: SaiRS/xxx-animation
          branch: feature/example

before_install: cd packages/example
install: npm install
after_success: npm run build
notifications:
  email:
    recipients:
      - xjiaxiang_86@163.com
    on_success: always
    on_failure: always
