langauge: node_js
node_js: "10"

jobs:
  include:
    - language: node_js
      node_js: "10"
      name: "build-1"
    - language: node_js
      node_js: "10"
      name: "build-2"

before_install: "cd packages/example"
install: "npm install"

script: "npm test" # 默认执行的脚本
after_success: "npm run build"

notifications:
  email:
    recipients:
      - xjiaxiang_86@163.com
    on_success: always # default: change
    on_failure: always # default: always
