language: node_js
node_js: '10'
stages:
  - stage-2
  - name: build
    if: branch = feature/example
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: build
      language: node_js
      node_js: '10'
      name: build-1
      deploy:
        provider: npm
        skip_cleanup: true
        email: xjiaxiang86@gmail.com
        api_token: env(NPM_TOKEN)
        #api_token:
        # secure: f9VA6c6BIu4u2HDUN1PHsGjR3TOXQxGNamsoOI6IIhdHJOuDuLjjXVE/ocj6ISRSYPEDnXmd7UjWaY6IZJgCcOj/G+REl1YY4A/itUVEMNQ+PtaRbs7KZcaUmes12/wxQfLagu0bKdQbsqxrzrD3pIwpUyImWLuU8Vt5GTcxfC2s3YTKd/vv+DJ9DIbE5JNcPoy+br41+gPwoIZV6doFVifXgydHrfEp1YKrh4v9OIbqS1JJXVhqBVh4ASvVJp3Pzrdw2kLoWInryQIOXPFwHpScfO+IIQ4Gmg2XxDCA+Qv0aBaoko3NtnVDG1N6v71mvoomKrelKBYLxPWz6Nkg3WJsO15v7d+9GbJImuUZHxRQmu0VFjTP/80AiuhGDQAOm7UCRMsXThKqKF/17r/oDI7Sb+PL4cQcZ42ZGeJ3MJTK9zb1B7P5WJIRn907qkRS0XsYHSXWtn2Q3aIDXw4LAB3hLphvyEJFT0y0rEYUKL+Z0gKUzFODvwxLBFkFQlzD+Q3apf48laIXU5uGq4T1+Eave2zqESRh/cJw6DsO1USHYSQl4CYEg6S9j8rhscUK0TjUmL8s5uD9VGlyyS4RfqzTHbgSiCF7Y54TEPR8XN2FnrHh6j6vY49KzNfljhZ0C80XHfwUcQhZ2VJH3JOfCAru3FOVwKKrOvrMO2NHDEw=
        on:
          repo: SaiRS/xxx-animation
          branch: feature/example
    - language: node_js
      stage: build-2
      node_js: '10'
      name: build-2
      install: skip
      script: skip

before_install: cd packages/example
install: npm install
after_success: npm run build

notifications:
  email:
    recipients:
      - xjiaxiang_86@163.com
    on_success: always
    on_failure: always
