langauge: node_js
node_js: "10"

stages:
  - stage-2
  - name: build
    if: branch = feature/example

script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: "build"
      language: node_js
      node_js: "10"
      name: "build-1"
    - language: node_js
      stage: "build-2"
      node_js: "10"
      name: "build-2"
      install: skip
      script: skip

# 全局的
before_install: "cd packages/example"
install: "npm install"

# script: "npm test" # 默认执行的脚本
after_success: "npm run build"

notifications:
  email:
    recipients:
      - xjiaxiang_86@163.com
    on_success: always # default: change
    on_failure: always # default: always
